name: '이슈 생성'
description: 'GitHub REST API를 사용하여 이슈를 생성한다'

inputs:
  title:
    description: '생성할 이슈의 제목'
    required: true
  content:
    description: '생성할 이슈의 내용'
    required: true
  label:
    description: '생성할 이슈의 라벨'
  repository:
    description: '이슈를 생성할 저장소. 예시) octocat/Hello-World'
    default: ${{ github.repository }}
  token:
    description: 'Create Issue GitHub API 호출을 위해 필요한 토큰'
    default: ${{ github.token }}

outputs:
  number:
    description: '생성된 이슈의 번호'
    value: ${{ steps.create-issue.outputs.number }}

runs:
  using: 'composite'
  steps:
    - name: '이슈를 생성한다'
      id: create-issue
      env:
        ISSUE_TOKEN: ${{ inputs.token }}
        ISSUE_REPOSITORY: ${{ inputs.repository }}
        ISSUE_TITLE: ${{ inputs.title }}
        ISSUE_CONTENT: ${{ inputs.content }}
        ISSUE_LABEL: ${{ inputs.label }}
      shell: bash
      run: python -m sends.github.main