name: 'Setup'
description: '프로젝트 실행에 필요한 기본 설정'

runs:
  using: "composite"
  steps:
    - name: '파이썬 설치'
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: '파이썬 의존성 패키지 설치'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Selenium 사용을 위한 Chrome Driver 설치'
      uses: nanasess/setup-chromedriver@v1.1.0